### ISSUE TITLE
macOS icon

### ISSUE THREAD

**Issue by ShlomoCode** [Fernthedev/desktop_adb_file_browser#19]
Made with Google Imagen 3, do with it as you wish :)

![image_fx_](https://github.com/user-attachments/assets/d7586794-3888-4600-8fab-929be20a7846)

**Comment by ShlomoCode** [comment]
from https://macosicons.com (see [How to change app icons on macOS Big Sur & Monterey](https://macosicons.com/#/how-to))
<img width="512" alt="60eb11d73c61c1e621873167e48ab259_tV6DrEph5O" src="https://github.com/user-attachments/assets/9c235fc9-50a8-44e8-9962-e50b6faed60e">
<img width="512" alt="10739c4ffad6d0d6f065c9b32b7c4d3b_BIJfqfNu23" src="https://github.com/user-attachments/assets/5a66c612-4cd1-4a41-9419-bb519af69dd8">

**Comment by Fernthedev** [comment]
Hi, thanks for your contribution! I appreciate the interest in having a nice icon but I can't accept these since they are:
- AI generated, morally and legally controversial.
- MacOS specific, which this software is not.

I'll think about giving this a proper icon some day though, thanks for reminding me.
